name: Remove old artifacts

on:
  schedule:
    # At 00:00 on day-of-month 1
    - cron: '0 0 1 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5

    - name: Protect GitHub Actions Artifacts
      uses: PaloAltoNetworks/upload-secure-artifact@main
      with:
        name: python-build
        path: /output
