name: Update module assets (daily)

on:
  schedule:
    - cron: "5 8 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for Git to git push
    name: Update module assets
    runs-on: ubuntu-latest
    steps:
      - name: Repo check
        run: |
          if [[ "$GITHUB_REPOSITORY_OWNER" != "Summer-CMS-Vendor-Packages" ]]; then
            echo "This GitHub Action is meant to deliver filter lists for sc-block-bad-crypto-filter-lists."
            echo "You shouldn't need to run this GitHub Action in your fork."
            echo "If you do, please customize the cron expression above."
            exit 1
          fi
          exit 0
      - name: Clone uAssets
        uses: actions/checkout@v4
      - name: Fetch module assets
        run: |
          ./tools/update-modules.sh
      - name: Commit changes, if any
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "github-actions bot"
            git config user.email "<>"
            git add -u thirdparties/
            git commit -m "Update all module assets"
            git push origin master
          fi
